version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: orphan_care
      POSTGRES_USER: orphancare
      POSTGRES_PASSWORD: orphancare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orphan_care
      SPRING_DATASOURCE_USERNAME: orphancare
      SPRING_DATASOURCE_PASSWORD: orphancare
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

volumes:
  postgres_data:
